dotenv: .env
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  development:
    verify: False
  rinkeby:
    verify: True
    eth_usd_priceFeed: "0x9326BFA02ADD2366b30bacB125260Af641031331"
  mainnet-fork-dev:
    verify: False
    eth_usd_priceFeed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
  ganache-local:
    verify: False
