dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

dependencies:
  # - aave/protocol-v2@1.0.1
  - smartcontractkit/chainlink-brownie-contracts@1.2.0
  - OpenZeppelin/openzeppelin-contracts@4.4.0
compiler:
  solc:
    remappings:
      # - "@aave=aave/protocol-v2@1.0.1"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0"

networks:
  default: ${DEFAULT_NETWORK:-development}

  development:
    default_config_network: rinkeby

  rinkeby:
    contracts:
      tokens:
        link: "0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B"
    config:
      verify: True
      # Example, Chainlink VRF keyhash parameter
      # vrf:
      #   keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
